{{- if .Values.nodeExporterSimulator.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter-simulator
  namespace: {{ .Values.namespace }}
  labels:
    app: node-exporter-simulator
spec:
  selector:
    matchLabels:
      app: node-exporter-simulator
  template:
    metadata:
      labels:
        app: node-exporter-simulator
    spec:
      serviceAccountName: node-exporter-simulator-account
      containers:
        - name: metrics-generator
          image: dev0guy/node-exporter-simulator:v1.0.6
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROMETHEUS_GATEWAY_URL
              value: "prometheus-gateway:9091"
            - name: PUSH_INTERVAL
              value:  {{ .Values.nodeExporterSimulator.interval }}
      dependsOn:
        - podName: prometheus-gateway
           condition: "Ready"
        - service:
            name: prometheus-gateway
{{- end }}