apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.prometheusGateway.replicaCount }}
  selector:
    matchLabels:
      app: prometheus-gateway
  template:
    metadata:
      labels:
        app: prometheus-gateway
    spec:
       containers:
        - name: pushgateway
          image: prom/pushgateway
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: prometheus-gateway
  ports:
    - name: http
      port: 9091
      targetPort: 9091